import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Providers } from "./Provider";  
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: raleway.style.fontFamily }} >

    {/* <Suspense> */}
        <Providers> 
          {children}  
          <Toaster />
        </Providers>
        {/* </Suspense> */}
      </body>
    </html>
  );
}
