import type { IUser } from "./user"

export interface IEvent {
    "id": string,
    "createdDate": number,
    "lastModifiedBy": IUser,
    "createdBy":IUser,
    "lastModifiedDate": number,
    "isDeleted": boolean,
    "picUrls": Array<string>,
    "eventMemberRole": any,
    "eventName": "Wiz",
    "eventDescription": "Roll one, smoke one",
    "eventType": "Birthday_Party",
    "locationType": string,
    "currency": "NGN",
    "currentPicUrl": string,
    "eventFunnelGroupID": string,
    "mediaType": any,
    "currentVideoUrl": any,
    "donationName": any,
    "affiliateID": any,
    "isPublic": boolean,
    "isExclusive": boolean,
    "mask": boolean,
    "isOrganizer": boolean,
    "attendeesVisibility": boolean,
    "isJoined": boolean,
    "isSaved": boolean,
    "isFree": boolean,
    "isBought": boolean,
    "ticketBought": boolean,
    "externalEvent": any,
    "donationEnabled": any,
    "minPrice": number,
    "maxPrice": number,
    "donationTargetAmount": any,
    "totalDonated": any,
    "startTime": number,
    "endTime": number,
    "startDate": number,
    "endDate": number,
    "expirationDate": any,
    "memberCount": number,
    "boughtTickets": number,
    "scannedTickets": number,
    "prStatus": string,
    "location": {
        "link": string,
        "links": Array<[
            string
        ]>,
        "address": string,
        "locationDetails": string,
        "latlng": string,
        "placeIds": any,
        "toBeAnnounced": boolean
    },
    "productTypeData": Array<{
        "totalNumberOfTickets": number,
        "ticketPrice": number,
        "ticketType": string,
        "ticketsSold": number,
        "sale": any,
        "minTicketBuy": number,
        "maxTicketBuy": number,
        "rerouteURL": string,
        "clickThroughCount": any,
        "startTime": number,
        "endTime": number,
        "startDate": number,
        "endDate": number
    }>,
    "interestedUsers": Array<any>,
    "collaborators": Array<any>,
    "admins": Array<any>,
    "acceptedCollaborators": Array<any>,
    "acceptedAdmins": Array<any>,
    "affiliates": Array<
        {
            "affiliateType": string,
            "percent": any
        }
    >
}