import type { IUser } from "./user"

export interface IFundraising {
    "id": string,
    "createdDate": number,
    "lastModifiedBy": any,
    "createdBy": IUser,
    "lastModifiedDate": number,
    "isDeleted": boolean,
    "status": any,
    "statusCode": number,
    "returnMessage": string,
    "user": IUser,
    "name": string,
    "description": string,
    "bannerImage": string,
    "fundRaisers": any,
    "expirationDate": any,
    "fundRasingGroupId": {
        "id": string,
        "createdDate": number,
        "createdAt": string,
        "lastModifiedBy": any,
        "createdBy": string,
        "lastModifiedDate": number,
        "isDeleted": boolean,
        "status": string,
        "creatorID": string,
        "name": string,
        "bannerImage": string,
        "description": string,
        "expirationDate": number
    },
    "goal": number,
    "total": number,
    "visibility": string,
    "collaborators": any,
    "purpose": string,
    "funnelID": any,
    "funnelType": any,
    "endDate": number,
    "isCollaborator": boolean,
    "totalInGroup": number
}